/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JEdit;
import Guidashboard.UserProfile;
     import java.sql.ResultSet;
    import net.proteanit.sql.DbUtils; // Requires rs2xml.jar
     import javax.swing.JOptionPane;

/**
 *
 * @author naval
 */
public class UserReports extends javax.swing.JFrame {
        public UserReports() {
        initComponents();
        System.out.println("DB PATH: " + new java.io.File("PCut_db.db").getAbsolutePath()); // temporary
        displayData();
    }

    public void displayData() {
       try {
        config.db_pcut db = new config.db_pcut();
        // This query selects specific columns from your 'users' table
        String sql = "SELECT user_id AS 'ID', user_fname AS 'First Name', "
                   + "user_lname AS 'Last Name', user_email AS 'Email', "
                   + "user_role AS 'Role' FROM users";

        ResultSet rs = db.getData(sql);
        user_table.setModel(DbUtils.resultSetToTableModel(rs));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error loading table: " + e.getMessage());
    }
    
    /**
     * Creates new form UserReports
     */
  
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        user_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        search_bar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 240, 235));

        user_table.setAutoCreateRowSorter(true);
        user_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Account_ID", "Name", "Email"
            }
        ));
        user_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(user_table);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Search User:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(92, 64, 51));
        jLabel2.setText("ALL REGISTERED USERS");

        search_bar.setText("LastName");
        search_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_barActionPerformed(evt);
            }
        });
        search_bar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_barKeyReleased(evt);
            }
        });

        jButton1.setText("Clear/Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(44, 44, 44));
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("DELETE USER");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lahisad.png"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(139, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_back)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(search_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btn_delete))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(276, 276, 276)
                    .addComponent(jLabel2)
                    .addContainerGap(391, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_back))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(search_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete)
                        .addGap(40, 40, 40)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel2)
                    .addContainerGap(581, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void search_barKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_barKeyReleased
                                     
    searchData(); 

    }//GEN-LAST:event_search_barKeyReleased

    private void search_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_barActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_barActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                       
    search_bar.setText("");
    displayData(); // This calls your original method that loads everything

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // Create an instance of the UserProfile frame
    UserProfile up = new UserProfile();
    
    // Make the UserProfile visible
    up.setVisible(true);
    
    // Close the current Reports frame
    this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
       int rowIndex = user_table.getSelectedRow();
    
    if (rowIndex < 0) {
        JOptionPane.showMessageDialog(this, "Please select a user from the table first!");
    } else {
        // Confirm the deletion
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this user?", "Warning", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                config.db_pcut db = new config.db_pcut();
                // Get the ID from the first column (Column 0) of the selected row
                String id = user_table.getValueAt(rowIndex, 0).toString();
                
                // SQL to delete
                String sql = "DELETE FROM users WHERE user_id = ?";
                db.deleteRecord(sql, id);
                
                // Refresh the table to show the user is gone
                displayData();
                JOptionPane.showMessageDialog(this, "User deleted successfully!");
            } catch (Exception e) {
                System.out.println("Delete Error: " + e.getMessage());
            }
        }
    }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  int row = user_table.getSelectedRow();
    
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a user to update!");
        return;
    }

    // Get data directly from the selected table row
    String id    = user_table.getValueAt(row, 0).toString();
    String fname = user_table.getValueAt(row, 1).toString();
    String lname = user_table.getValueAt(row, 2).toString();
    String email = user_table.getValueAt(row, 3).toString();
    String role  = user_table.getValueAt(row, 4).toString();

    // Validation
    if (fname.isEmpty() || lname.isEmpty() || email.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fields cannot be empty!");
        return;
    }

    // Confirm before updating
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to update this user?", "Confirm Update", 
        javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            config.db_pcut db = new config.db_pcut();
            String sql = "UPDATE users SET user_fname = ?, user_lname = ?, user_email = ?, user_role = ? WHERE user_id = ?";
            db.updateRecord(sql, fname, lname, email, role, id);

            displayData();
            javax.swing.JOptionPane.showMessageDialog(this, "User updated successfully!");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Update Error: " + e.getMessage());
        
    

        }
    
    

    

    // 4. Update Database
    config.db_pcut db = new config.db_pcut();
    String sql = "UPDATE users SET u_fname = ?, u_lname = ?, u_email = ?, u_type = ? WHERE u_id = ?";
   // db.updateRecord(sql, fname, lname, email, type, id);

    // 5. Refresh Table and Clear Fields
    displayUsers();
    javax.swing.JOptionPane.showMessageDialog(this, "User Updated Successfully!");

    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void user_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_tableMouseClicked
     // int row = user_table.getSelectedRow();
    
    // Fill your text fields with data from the selected row
    // Column indices: 0=ID, 1=First Name, 2=Last Name, 3=Email, 4=Type
  //  txtFirstName.setText(user_table.getValueAt(row, 1).toString());
    //txtLname.setText(user_table.getValueAt(row, 2).toString());
   // txtEmail.setText(user_table.getValueAt(row, 3).toString());
   // cbType.setSelectedItem(user_table.getValueAt(row, 4).toString());
    }//GEN-LAST:event_user_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search_bar;
    private javax.swing.JTable user_table;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JComboBox<String> cbType;
   public void searchData() {
    try {
        config.db_pcut db = new config.db_pcut();
        // The '%' symbols allow the database to find the text anywhere in the Last Name
        String sql = "SELECT user_id AS 'ID', user_fname AS 'First Name', "
                   + "user_lname AS 'Last Name', user_email AS 'Email', "
                   + "user_role AS 'Role' FROM users WHERE user_lname LIKE '%" + search_bar.getText() + "%'";
        
        ResultSet rs = db.getData(sql);
        user_table.setModel(DbUtils.resultSetToTableModel(rs));
    } catch (Exception e) {
        System.out.println("Search Error: " + e.getMessage());
    }
}

    private void displayUsers() {
      displayData ();
    }
}
