/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Guidashboard;
    
import History.HistoryFrame;
           import javax.swing.RowFilter;
           import javax.swing.table.TableRowSorter;
            import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import config.db_pcut; // Import your config class
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.xml.transform.Templates;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.File;
import java.awt.Desktop;

/**
 *
 * @author naval
 */
public class Inventory extends javax.swing.JFrame {
       private void filterTable(String query) {
   // Get whatever model is currently inside the table (from DbUtils)
    javax.swing.table.TableModel model = tblInventory.getModel();
    TableRowSorter<javax.swing.table.TableModel> sorter = new TableRowSorter<>(model);
    tblInventory.setRowSorter(sorter);

    if (query.trim().length() == 0 || query.equals("Search")) {
        sorter.setRowFilter(null);
    } else {
        // (?i) makes the search ignore uppercase/lowercase differences
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + query));
    }
}


    /**
     * Creates new form Inventory
     */
   public Inventory() {
    initComponents(); // This calls the GUI builder
    this.setLocationRelativeTo(null); 
    this.setResizable(false); 
    
    // Call the method to load the database data into the table
    displayTable();
    txtTransPrice.setEditable(false);
    lblTotalDisplay.setEditable(false);
    txtTransName.addKeyListener(new java.awt.event.KeyAdapter() {
    @Override
    public void keyReleased(java.awt.event.KeyEvent evt) {
        autoFillPrice();
    }
});

txtTransQty.addKeyListener(new java.awt.event.KeyAdapter() {
    @Override
    public void keyReleased(java.awt.event.KeyEvent evt) {
        calculateTotal();
    }
});

txtTransPrice.addKeyListener(new java.awt.event.KeyAdapter() {
    @Override
    public void keyReleased(java.awt.event.KeyEvent evt) {
        calculateTotal();
    }
});
    
    // Setup Search Logic
    txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt) {
            String query = txtSearch.getText();
            if(!query.equals("Search")) {
                filterTable(query);
            }
        }

        public void displayTable() {
    try {
        config.db_pcut db = new config.db_pcut();
        String sql = "SELECT p_id as 'ID', p_name as 'Product Name', p_stock as 'Stock (kg)', p_status as 'Status' FROM products";
        db.displayData(sql, tblInventory);
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
        }
        
    

    private void initComponents() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

  
    private void loadData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    });
}
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtButton = new javax.swing.JButton();
        btnAddStock = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTransName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTransPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTransQty = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblTotalDisplay = new javax.swing.JTextField();
        btnview = new javax.swing.JLabel();
        btnSell = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(70, 54, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/shortykabaw.png"))); // NOI18N

        txtButton.setBackground(new java.awt.Color(70, 54, 51));
        txtButton.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txtButton.setForeground(new java.awt.Color(255, 255, 255));
        txtButton.setText("Back");
        txtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtButtonActionPerformed(evt);
            }
        });

        btnAddStock.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAddStock.setText("ADD NEW STOCK");
        btnAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(txtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnAddStock))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnAddStock, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblInventory.setAutoCreateRowSorter(true);
        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Stock", "Status"
            }
        ));
        tblInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInventory);

        txtSearch.setText("Search");
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        lblMinimize.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(51, 0, 51));
        lblMinimize.setText("--");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });

        lblClose.setFont(new java.awt.Font("Yu Gothic", 1, 20)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 51, 102));
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Unit Price:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Product Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("TOTAL AMOUNT:");

        txtTransQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransQtyActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Enter Quantity (kg)");

        lblTotalDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTotalDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblTotalDisplayActionPerformed(evt);
            }
        });

        btnview.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnview.setText("View History");
        btnview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnviewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnviewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnviewMouseExited(evt);
            }
        });

        btnSell.setText("Purchase");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMinimize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSearch)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtTransName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtTransPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotalDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTransQty, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(144, 144, 144))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnSell)
                                        .addGap(166, 166, 166))))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(1072, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(299, 299, 299)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMinimize)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTransName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTransPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTransQty, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(btnSell)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnview)
                        .addGap(32, 32, 32))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(383, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtButtonActionPerformed
       Dashboard db = new Dashboard();
    db.setVisible(true);
    
    // Close the Inventory window
    this.dispose();
    }//GEN-LAST:event_txtButtonActionPerformed

    private void btnAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStockActionPerformed
     String role = config.Session.currentRole;
    
    if (role == null || !role.equalsIgnoreCase("Admin")) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Access Denied! Only Admins can add stock.", 
            "Permission Denied", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Open StockEntry form
    StockEntry se = new StockEntry(); 
    se.setVisible(true); 
    this.dispose();
    

 

  
    
    
    //StockEntry se = new StockEntry(); 
    se.setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_btnAddStockActionPerformed
private void generateReceipt(String name, String qty, String price, String total) {
    try {
       String path = System.getProperty("user.home") + "/Desktop/Receipt_" + System.currentTimeMillis() + ".pdf";
        Document doc = new Document();
        PdfWriter.getInstance(doc, new FileOutputStream(path));
        doc.open();
        doc.add(new Paragraph("********** PRIMECUT MEAT SHOP **********"));
        doc.add(new Paragraph("Customer Receipt"));
        doc.add(new Paragraph("Date: " + new java.util.Date().toString()));
        doc.add(new Paragraph("----------------------------------------"));
        doc.add(new Paragraph("Item: " + name));
        doc.add(new Paragraph("Quantity: " + qty + " kg"));
        doc.add(new Paragraph("Unit Price: PHP " + price));
        doc.add(new Paragraph("----------------------------------------"));
        doc.add(new Paragraph("TOTAL AMOUNT: PHP " + total));
        doc.add(new Paragraph("----------------------------------------"));
        doc.add(new Paragraph("Thank you for your purchase!"));
        doc.close();
        
        File file = new File(path);
        if (file.exists()) {
            Desktop.getDesktop().open(file);
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "PDF Error: " + e.getMessage());
    }
}


    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // This closes the current window
    this.dispose(); 
    
    // If this is the main window and you want to close the whole app, use:
    // System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
      // This command tells the JFrame to minimize to the taskbar
    this.setState(java.awt.Frame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
     lblMinimize.setOpaque(true);
    lblMinimize.setBackground(new java.awt.Color(220, 220, 220)); // Light Gray

    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
       lblMinimize.setOpaque(false);
    lblMinimize.setBackground(null);
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void lblTotalDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTotalDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTotalDisplayActionPerformed

    private void txtTransQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransQtyActionPerformed
        calculateTotal();
    }//GEN-LAST:event_txtTransQtyActionPerformed

    private void btnviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewMouseClicked
      new HistoryFrame().setVisible(true);
    // We don't use this.dispose() here so the user can keep the 
    // inventory open while checking logs.
    }//GEN-LAST:event_btnviewMouseClicked

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        sellProduct();
    }//GEN-LAST:event_btnSellActionPerformed

    private void tblInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventoryMouseClicked
        int row = tblInventory.getSelectedRow();
    if (row >= 0) {
        // Column 1 = Product Name
        String selectedName = tblInventory.getValueAt(row, 1).toString();
        txtTransName.setText(selectedName);
        autoFillPrice();
    }
    }//GEN-LAST:event_tblInventoryMouseClicked

    private void btnviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewMouseEntered
       btnview.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_btnviewMouseEntered

    private void btnviewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewMouseExited
    btnview.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnviewMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStock;
    private javax.swing.JButton btnSell;
    private javax.swing.JLabel btnview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JTextField lblTotalDisplay;
    private javax.swing.JTable tblInventory;
    private javax.swing.JButton txtButton;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTransName;
    private javax.swing.JTextField txtTransPrice;
    private javax.swing.JTextField txtTransQty;
    // End of variables declaration//GEN-END:variables

  private void loadData() {
  try {
        db_pcut db = new db_pcut(); // Your database config class
        ResultSet rs = db.getData("SELECT * FROM products"); // Or whatever your table name is
        // Use a library like RS2XML to easily fill the table
        // jTable1.setModel(DbUtils.resultSetToTableModel(rs)); 
    } catch (SQLException e) {
        System.out.println("Error: " + e.getMessage());
    }
}

    private void displayTable() {
     try {
        config.db_pcut db = new config.db_pcut();
        // This query fetches your products and gives them nice headers for the table
        String sql = "SELECT p_id as 'Product ID', p_name as 'Product Name', p_stock as 'Stock', p_status as 'Status' FROM products";
        db.displayData(sql, tblInventory); 
    } catch (Exception e) {
        System.out.println("Error loading table: " + e.getMessage());
    }
}

private void calculateTotal() {
    try {
        double price = Double.parseDouble(txtTransPrice.getText());
        double qty   = Double.parseDouble(txtTransQty.getText());
        double total = price * qty;
        lblTotalDisplay.setText(String.format("%.2f", total));
    } catch (NumberFormatException e) {
        lblTotalDisplay.setText("");
    }
}
private void sellProduct() {
    String name  = txtTransName.getText();
    String price = txtTransPrice.getText();
    String qty   = txtTransQty.getText();
    String total = lblTotalDisplay.getText();

    // ✅ Keep your original empty check
    if (name.isEmpty() || price.isEmpty() || qty.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!");
        return;
    }

    // ✅ ADD THIS: Stock check before showing confirm dialog
    try {
        config.db_pcut dbCheck = new config.db_pcut();
        java.sql.ResultSet rs = dbCheck.getData(
            "SELECT p_stock, p_status FROM products WHERE p_name = '" + name + "'"
        );
        if (rs.next()) {
            double currentStock = rs.getDouble("p_stock");
            String status = rs.getString("p_status");
            double requestedQty = Double.parseDouble(qty);

            if (status.equalsIgnoreCase("Not Available") || currentStock <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Sorry, " + name + " is currently OUT OF STOCK!",
                    "Out of Stock", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (requestedQty > currentStock) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Not enough stock! Only " + currentStock + " kg available.",
                    "Insufficient Stock", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Stock check error: " + e.getMessage());
        return;
    }

    // ✅ Your original confirm dialog — NOT changed
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "Confirm sale of " + qty + "kg of " + name + " for PHP " + total + "?",
        "Confirm Sale", javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            config.db_pcut db = new config.db_pcut();

            // ✅ Your original — NOT changed
            String userName = config.Session.getFname() + " " + config.Session.getLname();

            // ✅ Your original — NOT changed
            String histSql = "INSERT INTO transaction_history (product_name, quantity, total_price, date_sold, user_name) VALUES (?, ?, ?, datetime('now'), ?)";
            db.addRecord(histSql, name, qty, total, userName);

            // ✅ CHANGED: Now also auto-updates status to "Not Available" when stock hits 0
            String updateSql = "UPDATE products SET p_stock = p_stock - ?, " +
                "p_status = CASE WHEN (p_stock - ?) <= 0 THEN 'Not Available' ELSE p_status END " +
                "WHERE p_name = ?";
            db.updateRecord(updateSql, qty, qty, name);

            // ✅ Your original — NOT changed
            txtTransName.setText("");
            txtTransPrice.setText("");
            txtTransQty.setText("");
            lblTotalDisplay.setText("");

            // ✅ Your original — NOT changed
            displayTable();
            javax.swing.JOptionPane.showMessageDialog(this, "Sale recorded successfully!");
            generateReceipt(name, qty, price, total);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        
    
        }
    }
}
private void autoFillPrice() {
    try {
        String productName = txtTransName.getText();
        if (productName.isEmpty()) {
            txtTransPrice.setText("");
            lblTotalDisplay.setText("");
            return;
        }

        config.db_pcut db = new config.db_pcut();
        java.sql.ResultSet rs = db.getData(
            "SELECT p_price FROM products WHERE p_name = '" + productName + "'"
        );

        if (rs.next()) {
            String price = rs.getString("p_price");
            txtTransPrice.setText(price);
            calculateTotal(); // Auto calculate total too
        } else {
            txtTransPrice.setText("");
            lblTotalDisplay.setText("");
        }
    } catch (Exception e) {
        System.out.println("AutoFill Error: " + e.getMessage());
    }
}
}



